const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(),'kanpak-ui-'));
const base='http://127.0.0.1:5099';
const server=spawn('python',['server.py','--port','5099'],{cwd:__dirname,env:{...process.env,KANPAK_DB:path.join(temporary,'test.db')},windowsHide:true,stdio:'pipe'});
let browser;
(async()=>{
  for(let i=0;i<60;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  const page=await context.newPage();
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon.ico'))errors.push(m.text());});
  fs.mkdirSync(path.join(__dirname,'test-results'),{recursive:true});
  await page.goto(base);
  await page.waitForSelector('.machine-card');
  assert.equal(await page.locator('.machine-card').count(),6);
  assert.equal(await page.locator('.workload-person').count(),4);
  assert.equal(await page.locator('#shift option').count(),2);
  await page.screenshot({path:path.join(__dirname,'test-results','desktop.png'),fullPage:true});
  const initial=await (await fetch(base+'/api/state')).json();
  const conveyorOwner=initial.assignments.find(a=>a.machine_id===6 && a.shift==='Day').user_id;
  await page.locator('#person').selectOption(String(conveyorOwner));
  const card=page.locator('.machine-card').filter({hasText:'Case conveyor'});
  await card.getByRole('button',{name:'Start task'}).click();
  await page.getByRole('button',{name:'Start checklist'}).click();
  await page.waitForSelector('#task-form');
  for(const box of await page.locator('#task-form input[type=checkbox]').all())await box.check();
  for(let i=0;i<3;i++)await page.locator(`[name=q${i}][value="${i}"]`).check();
  await page.locator('#task-note').fill('Demo reference CS-001. Sample visual check recorded for presentation.');
  await page.getByRole('button',{name:'Continue later'}).click();
  await page.reload();
  await page.locator('.machine-card').filter({hasText:'Case conveyor'}).getByRole('button',{name:'Resume task'}).click();
  assert.equal(await page.locator('#task-form input[type=checkbox]:checked').count(),5);
  await page.getByRole('button',{name:'Submit for verification'}).click();
  await page.waitForFunction(()=>!document.querySelector('dialog').open);
  assert.match(await page.locator('.machine-card').filter({hasText:'Case conveyor'}).innerText(),/Needs review/);
  await page.locator('.sidebar [data-view=admin]').click();
  await page.locator('#password').fill('KanPakDemo!2026');
  await page.getByRole('button',{name:'Unlock workspace'}).click();
  await page.getByRole('button',{name:'Verify · award 25 XP'}).click();
  await page.locator('#review-note').fill('Supervisor demo: checklist and supporting reference checked.');
  await page.getByRole('button',{name:'Confirm verification'}).click();
  await page.waitForFunction(()=>!document.querySelector('dialog').open);
  await page.locator('.sidebar [data-view=team]').click();
  assert.match(await page.locator('.team-card').filter({hasText:initial.users.find(u=>u.id===conveyorOwner).name}).innerText(),/25 lifetime XP/);
  await page.locator('.sidebar [data-view=admin]').click();
  await page.getByRole('button',{name:'Team members',exact:true}).click();
  await page.getByRole('button',{name:'Shift assignments',exact:true}).click();
  const nightForm=page.locator('.roster-form[data-shift="Night"]');
  for(const box of await nightForm.locator('input').all()) await box.uncheck();
  await nightForm.locator('input[value="1"]').check();
  await nightForm.locator('input[value="2"]').check();
  await nightForm.getByRole('button',{name:'Save Night crew & balance tasks'}).click();
  await page.getByText('Shift crew saved. Unstarted tasks balanced.',{exact:true}).waitFor();
  const balanced=await (await fetch(base+'/api/state')).json();
  assert.deepEqual([...new Set(balanced.assignments.filter(a=>a.shift==='Night').map(a=>a.user_id))].sort(),[1,2]);
  assert.equal(balanced.runs.filter(r=>r.shift==='Day'&&r.status==='verified').length,1);
  await page.getByRole('button',{name:'Back to reviews'}).click();
  await page.getByRole('button',{name:'Team members',exact:true}).click();
  await page.locator('#u-name').fill('Demo Operator');
  await page.getByRole('button',{name:'Add team member'}).click();
  await page.waitForSelector('.admin-list-item:has-text("Demo Operator")');
  await page.getByRole('button',{name:'Equipment',exact:true}).click();
  await page.locator('#m-name').fill('Demo test machine');
  await page.locator('#m-area').fill('Test zone');
  await page.locator('#m-description').fill('Temporary browser test equipment');
  await page.locator('#m-steps').fill('Check approved site procedure.\nRecord the approved inspection result.');
  await page.getByRole('button',{name:'Add machine'}).click();
  await page.locator('.admin-list-item').filter({hasText:'Demo test machine'}).getByRole('button',{name:'Delete'}).click();
  await page.getByRole('button',{name:'Confirm removal'}).click();
  await page.waitForFunction(()=>!document.querySelector('dialog').open);
  assert.equal(await page.locator('.admin-list-item').filter({hasText:'Demo test machine'}).count(),0);
  // Independent employee browser sees shared persisted completion, without admin access.
  const employee=await browser.newContext({viewport:{width:390,height:844}});
  const mobile=await employee.newPage();
  mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto(base);
  await mobile.waitForSelector('.machine-card');
  assert.match(await mobile.locator('.machine-card').filter({hasText:'Case conveyor'}).innerText(),/Verified/);
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await mobile.screenshot({path:path.join(__dirname,'test-results','mobile.png'),fullPage:true});
  await mobile.locator('.sidebar [data-view=admin]').click();
  await mobile.waitForSelector('#login-form');
  await page.locator('.sidebar [data-view=records]').click();
  await page.getByRole('button',{name:'Details'}).click();
  assert.match(await page.locator('#modal-content').innerText(),/Supervisor demo/);
  await page.screenshot({path:path.join(__dirname,'test-results','record.png'),fullPage:true});
  // Ignore the browser's automatic favicon 404; all page errors and CSP failures must be absent.
  assert.deepEqual(errors.filter(e=>!e.includes('404 (Not Found)')),[]);
  console.log('PASS: desktop, mobile overflow, task draft, submission, admin verification, XP, add user, add/delete machine, shared clients, audit details.');
  console.log('Screenshots: test-results/desktop.png, mobile.png, record.png');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
